service: folderstack-auth

frameworkVersion: '3'
useDotenv: true

package:
    individually: false
    excludeDevDependencies: true

plugins:
    # - serverless-domain-manager
    - serverless-prune-plugin
    - serverless-esbuild
    - serverless-dynamodb-local
    - serverless-offline

custom:
    prune:
        automatic: true
        number: 1
    region: ap-southeast-2
    serviceName: auth
    currentStage: ${opt:stage, 'local'}
    logLevels:  
        production: warn
        staging: warn
        local: debug
    logLevel: ${self:custom.logLevels.${self:custom.currentStage}, 'info'}
    # customDomain:
    #     domainName: "auth.folderstack.io"
    #     stage: ${self:custom.currentStage}
    #     certificateName: "*.folderstack.io"
    #     createRoute53Record: true
    esbuild:
        bundle: true
        minify: false
        target: node16
        packager: yarn
        sourcemap: true
        sourcesContent: true
    serverless-offline:
        httpPort: 4000
        lambdaPort: 4001
    dynamodb:
        stages:
            - local
        start:
            migrate: true
            inMemory: true
            docker: true
            seed: true
        seed:
            testSeeds:
                sources:
                    - table: ${self:custom.table}
                      sources: [./test.seed.json]
    table: "folderstack-${self:custom.currentStage}"

provider:
    name: aws
    runtime: nodejs16.x
    region: ${self:custom.region}
    memorySize: 128
    environment:
        TABLE_NAME:
            Fn::ImportValue:
                "FolderStack-Table-Name-Export-${self:custom.currentStage}"
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '0'
        ENV: ${self:custom.currentStage}
        LOG_LEVEL: ${self:custom.logLevel, 'info'}
    iamRoleStatements:
       - Effect: "Allow"
         Action:
            - "dynamodb:Query"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
         Resource: 
            - "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.table}"

functions:
    - ${file(./sls/handlers.yaml)}